[package]
name = "unicornafl"
version = "3.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libafl_targets = { git = "https://github.com/AFLplusplus/LibAFL", features = ["pointer_maps", "forkserver", "cmplog"] }
libafl = { git = "https://github.com/AFLplusplus/LibAFL" }
libafl_bolts = { git = "https://github.com/AFLplusplus/LibAFL" }

serde ={ version = "1.0", features = ["derive"] }
unicorn-engine = { git = "https://github.com/unicorn-engine/unicorn", branch = "dev"}
log = "0.4"
nix = { version = "0.29", features = ["signal"] }
env_logger = { version = "0.11", optional = true }

[features]
default = []
bindings = ["unicorn-engine/dynamic_linkage"]

[[example]]
name = "sample"
